compiles

diff --git a/tgui/bin/tgui b/tgui/bin/tgui
--- a/tgui/bin/tgui
+++ b/tgui/bin/tgui
@@ -98,6 +98,19 @@ task-clean() {
   rm -f **/package-lock.json
 }
 
+## Validates current build against the build stored in git
+task-validate-build() {
+  cd "${base_dir}"
+  local diff
+  diff="$(git diff public/*)"
+  if [[ -n ${diff} ]]; then
+    echo "Error: our build differs from the build committed into git."
+    echo "Please rebuild tgui."
+    exit 1
+  fi
+  echo "tgui: build is ok"
+}
+
 ## Installs merge drivers and git hooks
 task-install-git-hooks() {
   cd "${base_dir}"
